import "server-only";
import { createClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { products as fallbackProducts, type Product, type ProductGalleryImage } from "@/lib/products";
import type { CollectionRow, ProductImageRow, ProductRow } from "@/lib/supabase/types";

function localFallback(slug:string){return fallbackProducts.find(item=>item.slug===slug);}
function imageUrl(path:string,url:string){return path.startsWith("http")||path.startsWith("/")?path:`${url}/storage/v1/object/public/product-images/${path}`;}
async function mapProducts(rows:ProductRow[]):Promise<Product[]>{
  const supabase=await createClient();const ids=rows.map(row=>row.id);
  const [{data:imageRows},{data:links},{data:collections}]=await Promise.all([ids.length?supabase.from("product_images").select("*").in("product_id",ids).order("sort_order"):Promise.resolve({data:[]} as {data:ProductImageRow[]}),ids.length?supabase.from("collection_products").select("product_id, collection_id").in("product_id",ids):Promise.resolve({data:[]} as {data:{product_id:string;collection_id:string}[]}),supabase.from("collections").select("*").eq("is_active",true)]);
  const storageUrl=process.env.NEXT_PUBLIC_SUPABASE_URL!;const collectionMap=new Map((collections??[]).map((collection:CollectionRow)=>[collection.id,collection]));
  return rows.map(row=>{const fallback=localFallback(row.slug);const databaseImages=(imageRows??[]).filter(image=>image.product_id===row.id).sort((a,b)=>a.sort_order-b.sort_order);let gallery:ProductGalleryImage[]=databaseImages.map(image=>({id:image.id,src:imageUrl(image.storage_path,storageUrl),alt:image.alt_text||row.name,isPrimary:image.is_primary}));if(!gallery.length&&fallback){gallery=[{src:fallback.image,alt:fallback.name,isPrimary:true},...(fallback.secondaryImage?[{src:fallback.secondaryImage,alt:`${fallback.name} portée`,isPrimary:false}]:[])];}const primary=gallery.find(image=>image.isPrimary)??gallery[0];const link=(links??[]).find(item=>item.product_id===row.id);const collection=link?collectionMap.get(link.collection_id):undefined;return {id:row.id,slug:row.slug,name:row.name,collection:collection?.name??"Collection",collectionSlug:collection?.slug,price:row.price/100,compareAt:row.compare_at_price?row.compare_at_price/100:undefined,image:primary?.src??"/images/photo0.png",secondaryImage:gallery.find(image=>image.src!==primary?.src)?.src,images:gallery.map(image=>image.src),gallery,badge:row.featured?"Pièce signature":undefined,stock:row.stock_quantity,lowStockThreshold:row.low_stock_threshold,sku:row.sku??"—",description:row.description??"",shortDescription:row.short_description??undefined,featured:row.featured,status:row.status,seoTitle:row.seo_title??undefined,seoDescription:row.seo_description??undefined,mainMaterial:row.main_material??undefined,findingsMaterial:row.findings_material??undefined,color:row.color??undefined,updatedAt:row.updated_at};});
}
export async function getPublicProducts(){if(!isSupabaseConfigured())return fallbackProducts;const supabase=await createClient();const {data,error}=await supabase.from("products").select("*").eq("status","active").order("featured",{ascending:false}).order("created_at",{ascending:false});if(error){console.error("Catalogue Supabase indisponible",error.message);return [];}return mapProducts(data);}
export async function getFeaturedProducts(limit=3){return (await getPublicProducts()).filter(product=>product.featured??true).slice(0,limit);}
export async function getPublicProduct(slug:string){if(!isSupabaseConfigured())return fallbackProducts.find(product=>product.slug===slug)??null;const supabase=await createClient();const {data,error}=await supabase.from("products").select("*").eq("slug",slug).eq("status","active").maybeSingle();if(error||!data)return null;return (await mapProducts([data]))[0]??null;}
export async function getPublicCollections(){if(!isSupabaseConfigured())return [{id:"fallback",slug:"eclat-nacre",name:"Éclat nacré",description:"Une collection douce et singulière.",introduction:null,seo_content:null,seo_title:null,seo_description:null,image_path:null,is_active:true,is_indexable:true,sort_order:0,created_at:new Date(0).toISOString(),updated_at:new Date(0).toISOString()}] satisfies CollectionRow[];const supabase=await createClient();const {data}=await supabase.from("collections").select("*").eq("is_active",true).order("sort_order");return data??[];}
export async function getPublicCollection(slug:string){if(!isSupabaseConfigured())return {slug,name:"Éclat nacré",description:"Une collection douce, organique et singulière.",introduction:null,seo_content:null,seo_title:null,seo_description:null,is_indexable:true,updated_at:new Date(0).toISOString(),products:fallbackProducts.filter(product=>product.collection==="Éclat nacré")};const supabase=await createClient();const {data:collection}=await supabase.from("collections").select("*").eq("slug",slug).eq("is_active",true).maybeSingle();if(!collection)return null;const {data:links}=await supabase.from("collection_products").select("product_id, sort_order").eq("collection_id",collection.id).order("sort_order");const ids=(links??[]).map(link=>link.product_id);if(!ids.length)return {...collection,products:[]};const {data:rows}=await supabase.from("products").select("*").in("id",ids).eq("status","active");return {...collection,products:await mapProducts(rows??[])};}
export async function getRelatedProducts(product:Product,limit=4){const all=await getPublicProducts();return all.filter(item=>item.slug!==product.slug).sort((a,b)=>Number(b.collectionSlug===product.collectionSlug)-Number(a.collectionSlug===product.collectionSlug)).slice(0,limit);}
