"use client";
import Image from "next/image";
import { ArrowLeft, ArrowRight, GripVertical, ImagePlus, Star, Trash2, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { MAX_PRODUCT_PHOTOS, validatePhotoSelection } from "@/lib/product-photo-validation";

export type ExistingProductPhoto={id:string;url:string;altText:string;isPrimary:boolean};
type PhotoItem={key:string;kind:"existing";id:string;preview:string;altText:string}|{key:string;kind:"new";file:File;preview:string;altText:string};
export function ProductPhotoManager({existing=[]}:{existing?:ExistingProductPhoto[]}) {
  const inputRef=useRef<HTMLInputElement>(null); const [items,setItems]=useState<PhotoItem[]>(()=>existing.map(photo=>({key:`existing:${photo.id}`,kind:"existing",id:photo.id,preview:photo.url,altText:photo.altText}))); const initialPrimary=existing.find(photo=>photo.isPrimary)?.id; const [primaryKey,setPrimaryKey]=useState(initialPrimary?`existing:${initialPrimary}`:items[0]?.key??""); const [error,setError]=useState(""); const [dragKey,setDragKey]=useState<string|null>(null); const [over,setOver]=useState(false);
  const syncFiles=(next:PhotoItem[])=>{if(!inputRef.current)return;const transfer=new DataTransfer();next.filter((item):item is Extract<PhotoItem,{kind:"new"}>=>item.kind==="new").forEach(item=>transfer.items.add(item.file));inputRef.current.files=transfer.files;};
  const commit=(next:PhotoItem[])=>{setItems(next);syncFiles(next);if(next.length&&!next.some(item=>item.key===primaryKey))setPrimaryKey(next[0].key);if(!next.length)setPrimaryKey("");};
  const addFiles=(files:File[])=>{if(!files.length)return;setError("");const selectionError=validatePhotoSelection(items.length,files);if(selectionError){setError(selectionError);return;}const added=files.map(file=>({key:`new:${crypto.randomUUID()}`,kind:"new" as const,file,preview:URL.createObjectURL(file),altText:""}));const next=[...items,...added];if(!primaryKey&&next[0])setPrimaryKey(next[0].key);commit(next);};
  const remove=(key:string)=>{const found=items.find(item=>item.key===key);if(found?.kind==="new")URL.revokeObjectURL(found.preview);commit(items.filter(item=>item.key!==key));};
  const move=(from:number,to:number)=>{if(to<0||to>=items.length)return;const next=[...items];const [item]=next.splice(from,1);next.splice(to,0,item);commit(next);};
  const plan=items.map(item=>{const base={altText:item.altText,isPrimary:item.key===primaryKey};return item.kind==="existing"?{kind:"existing",id:item.id,...base}:{kind:"new",newIndex:items.filter(entry=>entry.kind==="new").findIndex(entry=>entry.key===item.key),...base};});
  return <section className="bg-paper p-6"><div className="flex items-end justify-between gap-4"><div><h2 className="display text-2xl">Photos du produit</h2><p className="mt-2 text-sm text-muted">JPG, PNG ou WEBP · 8 Mo maximum par image</p></div><strong className="text-sm text-wine">{items.length} / {MAX_PRODUCT_PHOTOS} photos</strong></div><input type="hidden" name="photo_plan" value={JSON.stringify(plan)}/><input ref={inputRef} className="sr-only" id="product-images" type="file" name="images" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" multiple onChange={event=>{const files=Array.from(event.target.files??[]);event.target.value="";addFiles(files)}}/>
  <div onDragEnter={event=>{event.preventDefault();setOver(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setOver(false)} onDrop={event=>{event.preventDefault();setOver(false);addFiles(Array.from(event.dataTransfer.files))}} className={`mt-5 rounded-sm border-2 border-dashed px-5 py-8 text-center transition ${over?"border-wine bg-[#faf4f3]":"border-line bg-ivory/60"}`}><Upload className="mx-auto text-wine" strokeWidth={1.4}/><p className="mt-3 text-sm font-semibold">Glissez vos photos ici</p><p className="mt-1 text-xs text-muted">ou</p><label htmlFor="product-images" className="mt-3 inline-flex min-h-11 cursor-pointer items-center gap-2 bg-ink px-5 text-xs font-bold uppercase tracking-[.12em] text-white"><ImagePlus size={16}/>Ajouter des photos</label></div>{error&&<p role="alert" className="mt-4 bg-[#f6e5e5] p-3 text-sm text-wine">{error}</p>}
  {items.length>0&&<div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-3">{items.map((item,index)=><article draggable onDragStart={()=>setDragKey(item.key)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();event.stopPropagation();const from=items.findIndex(photo=>photo.key===dragKey);if(from>=0&&from!==index)move(from,index);setDragKey(null)}} className={`group relative border bg-white p-2 ${item.key===primaryKey?"border-wine":"border-line"}`} key={item.key}><div className="relative aspect-square overflow-hidden bg-ivory"><Image src={item.preview} alt={item.altText||`Aperçu photo ${index+1}`} fill sizes="(max-width: 768px) 45vw, 240px" className="object-cover" unoptimized={item.kind==="new"}/><span className="absolute left-2 top-2 grid size-8 place-items-center bg-paper/90 text-muted"><GripVertical size={16}/></span>{item.key===primaryKey&&<span className="absolute bottom-2 left-2 flex items-center gap-1 bg-wine px-2 py-1 text-[.6rem] font-bold uppercase tracking-wider text-white"><Star size={11} fill="currentColor"/>Principale</span>}</div><input aria-label={`Texte alternatif de la photo ${index+1}`} value={item.altText} onChange={event=>setItems(current=>current.map(photo=>photo.key===item.key?{...photo,altText:event.target.value}:photo))} maxLength={180} placeholder="Texte alternatif (facultatif)" className="mt-2 min-h-9 w-full border border-line px-2 text-xs"/><div className="mt-2 flex items-center justify-between gap-2"><div className="flex gap-1"><button type="button" onClick={()=>move(index,index-1)} disabled={index===0} className="grid size-9 place-items-center border border-line disabled:opacity-30" aria-label="Déplacer vers la gauche"><ArrowLeft size={15}/></button><button type="button" onClick={()=>move(index,index+1)} disabled={index===items.length-1} className="grid size-9 place-items-center border border-line disabled:opacity-30" aria-label="Déplacer vers la droite"><ArrowRight size={15}/></button></div><button type="button" onClick={()=>setPrimaryKey(item.key)} disabled={item.key===primaryKey} className="min-h-9 px-2 text-[.65rem] font-bold uppercase tracking-wide text-wine disabled:opacity-40"><Star className="mr-1 inline" size={13}/>Définir principale</button><button type="button" onClick={()=>remove(item.key)} className="grid size-9 place-items-center text-wine" aria-label="Supprimer la photo"><Trash2 size={16}/></button></div></article>)}</div>}</section>;
}
