import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ProductGrid } from "@/components/shop/product-grid";
import { Breadcrumb } from "@/components/seo/breadcrumb";
import { getPublicCollection } from "@/lib/catalog";
import { pageMetadata, truncate } from "@/lib/seo";
export const revalidate=60;
export async function generateMetadata({params}:PageProps<"/collections/[slug]">):Promise<Metadata>{const {slug}=await params;const collection=await getPublicCollection(slug);if(!collection)return {title:"Collection introuvable",robots:{index:false,follow:false}};const title=collection.seo_title||`${collection.name} | Bouclescence`;const description=collection.seo_description||truncate(collection.introduction||collection.description||`Découvrez la collection ${collection.name} de Bouclescence.`,155);return pageMetadata({title,description,path:`/collections/${slug}`,noIndex:!collection.is_indexable});}
export default async function CollectionPage({params}:PageProps<"/collections/[slug]">){const {slug}=await params;const collection=await getPublicCollection(slug);if(!collection)notFound();return <div className="shell py-12 sm:py-20"><Breadcrumb items={[{name:"Accueil",href:"/"},{name:"Boutique",href:"/boutique"},{name:collection.name,href:`/collections/${slug}`}]}/><header className="max-w-2xl"><p className="eyebrow text-wine">Collection</p><h1 className="display mt-3 text-6xl">{collection.name}</h1><p className="mt-5 leading-8 text-muted">{collection.introduction||collection.description}</p></header><ProductGrid products={collection.products} className="mt-14" />{!collection.products.length&&<p className="mt-12 text-muted">Aucune création n’est actuellement publiée dans cette collection.</p>}{collection.seo_content&&<section className="mt-20 max-w-3xl border-t border-line pt-12"><h2 className="display text-4xl">À propos de cette collection</h2><p className="mt-6 whitespace-pre-line leading-8 text-muted">{collection.seo_content}</p></section>}</div>}
