"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { cleanupProductPhotos, syncProductPhotos, validateProductPhotoInput } from "@/lib/supabase/product-images";
import type { ProductStatus } from "@/lib/supabase/types";

export type ActionState={error?:string;success?:string;fields?:Record<string,string[]>}|null;
const money=z.string().trim().regex(/^\d+(?:[.,]\d{1,2})?$/,"Montant invalide").transform(value=>Math.round(Number(value.replace(",","."))*100));
const optionalMoney=z.string().trim().transform(value=>value===""?null:value).pipe(z.union([z.null(),money]));
const productSchema=z.object({name:z.string().trim().min(2,"Nom requis").max(120),slug:z.string().trim().min(2).max(140).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/,"Slug invalide"),short_description:z.string().trim().max(240).optional(),description:z.string().trim().max(10000).optional(),price:money,compare_at_price:optionalMoney,sku:z.string().trim().max(80).optional(),stock_quantity:z.coerce.number().int().min(0),low_stock_threshold:z.coerce.number().int().min(0),status:z.enum(["draft","active","archived"]),seo_title:z.string().trim().max(120).optional(),seo_description:z.string().trim().max(320).optional()});
function parseProduct(formData:FormData){return productSchema.safeParse({name:formData.get("name"),slug:formData.get("slug"),short_description:formData.get("short_description"),description:formData.get("description"),price:formData.get("price"),compare_at_price:formData.get("compare_at_price"),sku:formData.get("sku"),stock_quantity:formData.get("stock_quantity"),low_stock_threshold:formData.get("low_stock_threshold"),status:formData.get("status"),seo_title:formData.get("seo_title"),seo_description:formData.get("seo_description")});}
async function syncCollections(productId:string,collectionIds:string[]){const supabase=await createClient();const {error:deleteError}=await supabase.from("collection_products").delete().eq("product_id",productId);if(deleteError)throw new Error(deleteError.message);if(collectionIds.length){const {error}=await supabase.from("collection_products").insert(collectionIds.map((collection_id,sort_order)=>({collection_id,product_id:productId,sort_order})));if(error)throw new Error(error.message);}}
function productValues(data:z.infer<typeof productSchema>,formData:FormData){const {stock_quantity,...values}=data;return {stockQuantity:stock_quantity,values:{...values,short_description:values.short_description||null,description:values.description||null,compare_at_price:values.compare_at_price,sku:values.sku||null,seo_title:values.seo_title||null,seo_description:values.seo_description||null,is_unique_piece:formData.get("is_unique_piece")==="on",featured:formData.get("featured")==="on",stock_tracking:true}};}
function refreshProductPaths(slug?:string){revalidatePath("/");revalidatePath("/boutique");revalidatePath("/admin/produits");if(slug)revalidatePath(`/produit/${slug}`);}

export async function createProduct(_:ActionState,formData:FormData):Promise<ActionState>{await requireAdmin();const parsed=parseProduct(formData);if(!parsed.success)return {error:"Vérifiez les champs indiqués.",fields:parsed.error.flatten().fieldErrors};const {stockQuantity,values}=productValues(parsed.data,formData);if(values.is_unique_piece&&stockQuantity>1)return {error:"Le stock d’une pièce unique ne peut pas dépasser 1."};try{await validateProductPhotoInput(formData);}catch(error){return {error:error instanceof Error?error.message:"Photos invalides."};}const supabase=await createClient();const {data,error}=await supabase.from("products").insert({...values,stock_quantity:0}).select("id").single();if(error)return {error:error.code==="23505"?"Ce slug ou ce SKU existe déjà.":error.message};try{await syncProductPhotos(data.id,formData);await syncCollections(data.id,formData.getAll("collections").map(String));if(stockQuantity>0){const {error:stockError}=await supabase.rpc("adjust_inventory",{p_product_id:data.id,p_quantity_change:stockQuantity,p_reason:"Stock initial",p_movement_type:"initial"});if(stockError)throw new Error(stockError.message);}}catch(error){await cleanupProductPhotos(data.id);await supabase.from("products").delete().eq("id",data.id);return {error:`Le produit n’a pas été créé : ${error instanceof Error?error.message:"erreur inconnue"}`};}refreshProductPaths(values.slug);redirect(`/admin/produits/${data.id}?created=1`);}

export async function updateProduct(productId:string,_:ActionState,formData:FormData):Promise<ActionState>{await requireAdmin();if(!z.string().uuid().safeParse(productId).success)return {error:"Identifiant invalide."};const parsed=parseProduct(formData);if(!parsed.success)return {error:"Vérifiez les champs indiqués.",fields:parsed.error.flatten().fieldErrors};const {stockQuantity,values}=productValues(parsed.data,formData);if(values.is_unique_piece&&stockQuantity>1)return {error:"Le stock d’une pièce unique ne peut pas dépasser 1."};try{await validateProductPhotoInput(formData);}catch(error){return {error:error instanceof Error?error.message:"Photos invalides."};}const supabase=await createClient();const {data:current}=await supabase.from("products").select("stock_quantity").eq("id",productId).single();let photoWarning:string|null=null;try{photoWarning=(await syncProductPhotos(productId,formData)).warning;}catch(error){return {error:error instanceof Error?error.message:"Les photos n’ont pas pu être enregistrées."};}const {error}=await supabase.from("products").update(values).eq("id",productId);if(error)return {error:error.message};if(current&&current.stock_quantity!==stockQuantity){const {error:stockError}=await supabase.rpc("adjust_inventory",{p_product_id:productId,p_quantity_change:stockQuantity-current.stock_quantity,p_reason:"Mise à jour depuis la fiche produit",p_movement_type:"manual_adjustment"});if(stockError)return {error:stockError.message};}try{await syncCollections(productId,formData.getAll("collections").map(String));}catch(error){return {error:error instanceof Error?error.message:"Erreur de collection."};}refreshProductPaths(values.slug);return {success:photoWarning?`Produit enregistré. ${photoWarning}`:"Produit et photos enregistrés."};}

export async function archiveProduct(formData:FormData){await requireAdmin();const id=z.string().uuid().parse(formData.get("id"));const supabase=await createClient();const {error}=await supabase.from("products").update({status:"archived" as ProductStatus}).eq("id",id);if(error)throw new Error(error.message);refreshProductPaths();}
export async function adjustStock(_:ActionState,formData:FormData):Promise<ActionState>{await requireAdmin();const schema=z.object({product_id:z.string().uuid(),variant_id:z.string().uuid().nullable(),quantity_change:z.coerce.number().int().refine(v=>v!==0,"La variation ne peut pas être nulle."),reason:z.string().trim().min(3,"Une raison est obligatoire.")});const parsed=schema.safeParse({product_id:formData.get("product_id"),variant_id:formData.get("variant_id")||null,quantity_change:formData.get("quantity_change"),reason:formData.get("reason")});if(!parsed.success)return {error:parsed.error.issues[0]?.message};const supabase=await createClient();const {error}=await supabase.rpc("adjust_inventory",{p_product_id:parsed.data.product_id,p_variant_id:parsed.data.variant_id,p_quantity_change:parsed.data.quantity_change,p_reason:parsed.data.reason,p_movement_type:"manual_adjustment"});if(error)return {error:error.message};revalidatePath("/admin/stocks");revalidatePath("/admin/produits");return {success:"Stock ajusté et mouvement enregistré."};}
export async function createVariant(formData:FormData){await requireAdmin();const parsed=z.object({product_id:z.string().uuid(),name:z.string().trim().min(1),sku:z.string().trim().min(1),price:z.string(),stock_quantity:z.coerce.number().int().min(0)}).parse({product_id:formData.get("product_id"),name:formData.get("name"),sku:formData.get("sku"),price:formData.get("price"),stock_quantity:formData.get("stock_quantity")});const price=parsed.price.trim()?Math.round(Number(parsed.price.replace(",","."))*100):null;if(price!==null&&(!Number.isInteger(price)||price<0))throw new Error("Prix de variante invalide");const supabase=await createClient();const {data,error}=await supabase.from("product_variants").insert({product_id:parsed.product_id,name:parsed.name,sku:parsed.sku,price,stock_quantity:0,options:{},is_active:true,stock_tracking:true,sort_order:0}).select("id").single();if(error)throw new Error(error.message);if(parsed.stock_quantity>0){const {error:stockError}=await supabase.rpc("adjust_inventory",{p_product_id:parsed.product_id,p_variant_id:data.id,p_quantity_change:parsed.stock_quantity,p_reason:"Stock initial de la variante",p_movement_type:"initial"});if(stockError)throw new Error(stockError.message);}revalidatePath(`/admin/produits/${parsed.product_id}`);}
export async function toggleVariant(formData:FormData){await requireAdmin();const parsed=z.object({id:z.string().uuid(),product_id:z.string().uuid(),is_active:z.enum(["true","false"])}).parse({id:formData.get("id"),product_id:formData.get("product_id"),is_active:formData.get("is_active")});const supabase=await createClient();const {error}=await supabase.from("product_variants").update({is_active:parsed.is_active!=="true"}).eq("id",parsed.id);if(error)throw new Error(error.message);revalidatePath(`/admin/produits/${parsed.product_id}`);}
const collectionSchema=z.object({name:z.string().trim().min(2).max(120),slug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),description:z.string().trim().max(2000),introduction:z.string().trim().max(2000),seo_content:z.string().trim().max(10000),seo_title:z.string().trim().max(120),seo_description:z.string().trim().max(320),sort_order:z.coerce.number().int().min(0)});
function parseCollection(formData:FormData){return collectionSchema.parse({name:formData.get("name"),slug:formData.get("slug"),description:formData.get("description")??"",introduction:formData.get("introduction")??"",seo_content:formData.get("seo_content")??"",seo_title:formData.get("seo_title")??"",seo_description:formData.get("seo_description")??"",sort_order:formData.get("sort_order")});}
function collectionValues(data:z.infer<typeof collectionSchema>,formData:FormData){return {...data,description:data.description||null,introduction:data.introduction||null,seo_content:data.seo_content||null,seo_title:data.seo_title||null,seo_description:data.seo_description||null,is_indexable:formData.get("is_indexable")==="on"};}
export async function createCollection(formData:FormData){await requireAdmin();const parsed=parseCollection(formData);const supabase=await createClient();const {error}=await supabase.from("collections").insert({...collectionValues(parsed,formData),is_active:true});if(error)throw new Error(error.message);revalidatePath("/admin/collections");revalidatePath("/boutique");}
export async function updateCollection(formData:FormData){await requireAdmin();const id=z.string().uuid().parse(formData.get("id"));const parsed=parseCollection(formData);const values=collectionValues(parsed,formData);const supabase=await createClient();const {error}=await supabase.from("collections").update(values).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/admin/collections");revalidatePath(`/collections/${values.slug}`);revalidatePath("/sitemap.xml");}
export async function toggleCollection(formData:FormData){await requireAdmin();const parsed=z.object({id:z.string().uuid(),is_active:z.enum(["true","false"])}).parse({id:formData.get("id"),is_active:formData.get("is_active")});const supabase=await createClient();const {error}=await supabase.from("collections").update({is_active:parsed.is_active!=="true"}).eq("id",parsed.id);if(error)throw new Error(error.message);revalidatePath("/admin/collections");revalidatePath("/boutique");}
export async function logout(){const supabase=await createClient();await supabase.auth.signOut();redirect("/admin/login");}
