import Link from "next/link";
import type { Metadata } from "next";
import { Boxes, ChartNoAxesCombined, CirclePercent, ContactRound, Gem, PackageOpen, Settings, ShoppingBag, Tags, Truck } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { logout } from "@/app/admin/actions";
export const dynamic = "force-dynamic";
export const metadata:Metadata={title:"Administration",robots:{index:false,follow:false}};
const nav=[{href:"/admin",label:"Vue d’ensemble",icon:ChartNoAxesCombined},{href:"/admin/produits",label:"Produits",icon:Gem},{href:"/admin/commandes",label:"Commandes",icon:ShoppingBag},{href:"/admin/clients",label:"Clients",icon:ContactRound},{href:"/admin/collections",label:"Collections",icon:Tags},{href:"/admin/stocks",label:"Stocks",icon:Boxes},{href:"/admin/livraison",label:"Livraison",icon:Truck},{href:"/admin/promotions",label:"Promotions",icon:CirclePercent},{href:"/admin/parametres",label:"Paramètres",icon:Settings}];
export default async function AdminLayout({children}:{children:React.ReactNode}) { const admin=await requireAdmin(); return <div className="relative z-10 min-h-screen bg-[#f3f1ed]"><div className="grid min-h-screen md:grid-cols-[15rem_1fr]"><aside className="border-r border-line bg-ink px-5 py-7 text-white"><Link href="/" className="display text-2xl tracking-wide">Bouclescence</Link><p className="mt-1 text-[.6rem] uppercase tracking-[.18em] text-white/50">Administration</p><nav className="mt-10 flex flex-row gap-2 overflow-x-auto md:flex-col">{nav.map(({href,label,icon:Icon})=><Link href={href} key={href} className="flex min-w-fit items-center gap-3 px-3 py-3 text-sm text-white/70 transition hover:bg-white/10 hover:text-white"><Icon size={17} strokeWidth={1.5}/>{label}</Link>)}</nav><div className="mt-10 hidden border-t border-white/10 pt-6 text-xs text-white/45 md:block"><PackageOpen className="mb-3" size={18}/><p>Catalogue Supabase</p><form action={logout}><button className="mt-4 underline underline-offset-4">Se déconnecter</button></form></div></aside><div><header className="flex h-20 items-center justify-between border-b border-line bg-paper px-6 sm:px-10"><div><p className="text-xs uppercase tracking-[.15em] text-muted">Espace de gestion</p><p className="mt-1 text-sm font-semibold">{admin.profile.full_name??admin.user.email}</p></div><span className="rounded-full bg-[#e7eee6] px-3 py-1 text-xs text-[#38603c]">Accès administrateur</span></header><main className="p-5 sm:p-10">{children}</main></div></div></div>; }
