import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { AddToCart } from "@/components/shop/add-to-cart";
import { ProductGallery } from "@/components/shop/product-gallery";
import { ProductCard } from "@/components/shop/product-card";
import { Breadcrumb } from "@/components/seo/breadcrumb";
import { getPublicProduct, getRelatedProducts } from "@/lib/catalog";
import { formatPrice } from "@/lib/products";
import { absoluteUrl, jsonLd, pageMetadata, truncate } from "@/lib/seo";
export const revalidate=60;
export async function generateMetadata({params}:PageProps<"/produit/[slug]">):Promise<Metadata>{const {slug}=await params;const product=await getPublicProduct(slug);if(!product)return {title:"Produit introuvable",robots:{index:false,follow:false}};const title=product.seoTitle||`${product.name} | Bouclescence`;const description=product.seoDescription||truncate(product.shortDescription||product.description||`Découvrez ${product.name}, une création Bouclescence.`,155);return pageMetadata({title,description,path:`/produit/${product.slug}`,image:product.image});}
export default async function ProductPage({params}:PageProps<"/produit/[slug]">){const {slug}=await params;const product=await getPublicProduct(slug);if(!product)notFound();const gallery=product.gallery??[{src:product.image,alt:product.name,isPrimary:true}];const related=await getRelatedProducts(product);const productUrl=absoluteUrl(`/produit/${product.slug}`);const structured={"@context":"https://schema.org","@type":"Product","@id":`${productUrl}#product`,name:product.name,description:truncate(product.description||product.shortDescription||product.name,5000),image:gallery.map(image=>absoluteUrl(image.src)),sku:product.sku==="—"?undefined:product.sku,brand:{"@type":"Brand",name:"Bouclescence"},url:productUrl,offers:{"@type":"Offer",url:productUrl,price:product.price.toFixed(2),priceCurrency:"EUR",availability:`https://schema.org/${product.stock>0?"InStock":"OutOfStock"}`,itemCondition:"https://schema.org/NewCondition"}};const crumbs=[{name:"Accueil",href:"/"},{name:product.collection,href:product.collectionSlug?`/collections/${product.collectionSlug}`:"/boutique"},{name:product.name,href:`/produit/${product.slug}`}];return <div className="shell py-8 sm:py-14"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(structured)}}/><Breadcrumb items={crumbs}/><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:gap-16"><ProductGallery images={gallery} productName={product.name}/><div className="lg:sticky lg:top-32 lg:self-start"><p className="eyebrow text-wine">{product.collection}</p><h1 className="display mt-3 text-5xl sm:text-6xl">{product.name}</h1><div className="mt-4 flex gap-3 text-lg"><span>{formatPrice(product.price)}</span>{product.compareAt&&<s className="text-muted">{formatPrice(product.compareAt)}</s>}</div><p className="mt-8 leading-8 text-muted">{product.description}</p><div className="mt-7 border-y border-line py-5 text-sm"><p className="flex items-center gap-2"><span className={`size-2 rounded-full ${product.stock>0?"bg-wine":"bg-muted"}`}/>{product.stock>0?`${product.stock} en stock`:"Rupture de stock"}</p></div><div className="mt-6"><AddToCart product={product}/></div>{product.collectionSlug&&<p className="mt-8 text-sm text-muted">Découvrir aussi la <a className="text-ink underline underline-offset-4" href={`/collections/${product.collectionSlug}`}>collection {product.collection}</a>.</p>}<div className="mt-9 border-t border-line pt-6 text-xs uppercase tracking-[.13em] text-muted">{product.sku!=="—"&&<>SKU · {product.sku}</>}</div></div></div>{related.length>0&&<section className="py-20 sm:py-28"><h2 className="display text-4xl sm:text-5xl">Vous aimerez aussi</h2><div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{related.map(item=><ProductCard key={item.slug} product={item}/>)}</div></section>}</div>}
