-- Enrichissement non destructif du catalogue Bouclescence et de son SEO national.
alter table public.products add column if not exists main_material text;
alter table public.products add column if not exists findings_material text;
alter table public.products add column if not exists color text;

with content(import_key, model_name, color, shape, short_description, visual_description) as (values
  ('bouclescence-photo-0','Éclat Ivoire','Ivoire et ton doré','Médaillon rond','Un médaillon ivoire ponctué d’éclats dorés, façonné en argile polymère et associé à des éléments en acier inoxydable. Une ligne lumineuse et facile à porter.','Son disque rond ivoire, animé d’inclusions à l’aspect doré et surmonté d’un petit élément circulaire, compose une silhouette sobre et lumineuse.'),
  ('bouclescence-photo-1','Fleur d’Ivoire','Ivoire et ton doré','Cascade florale','Une cascade de pétales ivoire aux délicats reflets dorés, en argile polymère avec des éléments en acier inoxydable. Un modèle floral au mouvement gracieux.','Ses pétales ivoire assemblés en cascade dessinent une fleur légère, ponctuée de fins éclats visuellement dorés et portée par un anneau texturé.'),
  ('bouclescence-photo-2','Étoile Nacrée','Ivoire nacré et ton doré','Feuille striée et étoile','Une forme ivoire nacrée finement striée, accompagnée d’une étoile à la finition dorée. L’argile polymère et l’acier inoxydable s’unissent dans un modèle céleste.','Sa pièce élancée, entre feuille et losange, présente un relief strié et une douce nuance nacrée, tandis qu’une étoile ajourée apporte une note céleste.'),
  ('bouclescence-photo-3','Halo Ivoire','Ivoire et ton doré','Anneau festonné','Un grand halo ivoire aux contours festonnés et aux reflets dorés, réalisé en argile polymère avec des éléments en acier inoxydable. Une paire graphique et élégante.','Son large anneau ouvert, rythmé par un bord festonné et de petites touches dorées, encadre le visage avec une présence assumée mais aérienne.'),
  ('bouclescence-photo-4','Lagon','Turquoise et ton doré','Éventail','Un éventail turquoise intense semé de détails dorés, en argile polymère avec des éléments en acier inoxydable. Une paire colorée qui capte joliment la lumière.','Sa silhouette en éventail rappelle un plumage stylisé : un bleu lagon vibrant, des reliefs graphiques et quelques éclats à la finition dorée.'),
  ('bouclescence-photo-5','Azur','Bleu cobalt et ton doré','Feuille striée','Une feuille bleu cobalt au relief strié et aux touches dorées, façonnée en argile polymère et associée à l’acier inoxydable. Une ligne franche et féminine.','Sa forme pointue, finement nervurée comme une feuille stylisée, révèle un bleu cobalt profond traversé par de subtils éclats dorés.'),
  ('bouclescence-photo-6','Céladon','Céladon et ton doré','Trois pétales','Trois pétales céladon suspendus à un feuillage doré composent cette paire en argile polymère et acier inoxydable. Un modèle frais, délicat et végétal.','Sa fleur à trois pétales, dans un vert d’eau très doux, s’accorde à un élément de feuillage à l’aspect doré pour une silhouette botanique.'),
  ('bouclescence-photo-7','Fleur de Nuit','Bleu cobalt et ton doré','Fleur sculptée','Une fleur bleu cobalt généreuse, rehaussée de touches dorées, en argile polymère avec des éléments en acier inoxydable. Une paire florale au caractère affirmé.','Ses nombreux pétales sculptés forment une fleur dense et expressive, dont le bleu profond est réveillé par de fins accents visuellement dorés.'),
  ('bouclescence-photo-8','Lotus Lagon','Turquoise et ton doré','Lotus ajouré','Un lotus turquoise en relief se superpose à une ligne florale dorée. Cette paire en argile polymère et acier inoxydable offre un dessin aérien et lumineux.','Une corolle turquoise modelée en relief se détache devant le contour ajouré d’un lotus à la finition dorée, créant un jeu de profondeur délicat.'),
  ('bouclescence-photo-9','Éventail Azur','Bleu cobalt et ton doré','Éventail','Un éventail bleu cobalt aux reliefs graphiques et aux éclats dorés, en argile polymère et acier inoxydable. Une paire vive qui accompagne le mouvement.','Sa forme en éventail ou plumage stylisé associe un bleu cobalt intense à de petites touches dorées qui soulignent ses lignes rayonnantes.'),
  ('bouclescence-photo-10','Lotus Céleste','Bleu pervenche et ton doré','Lotus ajouré','Un lotus bleu pervenche posé sur une fleur ajourée dorée, réalisé en argile polymère avec des éléments en acier inoxydable. Une création douce et aérienne.','Sa corolle bleu céleste, modelée pétale après pétale, dialogue avec un grand contour de lotus à l’aspect doré et à la géométrie légère.'),
  ('bouclescence-photo-11','Lotus Pétrole','Bleu pétrole et ton doré','Lotus ajouré','Un lotus bleu pétrole profond associé à un contour floral doré, en argile polymère et acier inoxydable. Un modèle élégant, graphique et contrasté.','La profondeur du bleu pétrole met en valeur les pétales en relief, superposés à une structure de lotus ajourée à la finition dorée.'),
  ('bouclescence-photo-12','Minuit Fleuri','Bleu nuit et ton doré','Fleur sculptée','Une grande fleur bleu nuit ponctuée de reflets dorés, façonnée en argile polymère et complétée d’éléments en acier inoxydable. Une présence florale sophistiquée.','Ses pétales nombreux et sculptés composent une floraison généreuse en bleu nuit, éclairée par des détails dorés et un délicat motif de feuillage.'),
  ('bouclescence-photo-13','Ronde Cobalt','Bleu cobalt et ton doré','Médaillon rond','Un médaillon bleu cobalt moucheté de doré, en argile polymère avec des éléments en acier inoxydable. Une forme ronde, moderne et facile à associer.','Son disque cobalt à la surface organique est ponctué de petites touches dorées, puis relié à un élément supérieur carré au dessin géométrique.'),
  ('bouclescence-photo-14','Soleil Safran','Jaune safran et ton doré','Feuille striée','Une feuille safran finement striée et parsemée d’éclats dorés, en argile polymère et acier inoxydable. Une paire chaleureuse qui illumine le visage.','Sa forme élancée aux nervures régulières évoque une feuille ou un pétale plissé, dans une nuance safran solaire relevée de doré.'),
  ('bouclescence-photo-15','Dahlia Noir','Noir et ton doré','Fleur sculptée','Une fleur noire sculptée, soulignée de détails dorés, en argile polymère avec des éléments en acier inoxydable. Une paire florale chic et contrastée.','Ses pétales noirs en relief forment un dahlia généreux, dont les contours et petites inclusions dorées apportent lumière et profondeur.'),
  ('bouclescence-photo-16','Feuille Nocturne','Noir et ton doré','Feuille striée','Une feuille noire au relief strié et aux reflets dorés, façonnée en argile polymère et associée à l’acier inoxydable. Un modèle graphique à l’élégance nocturne.','Sa silhouette pointue et nervurée allonge le port de tête, tandis que le noir profond et les touches dorées créent un contraste raffiné.'),
  ('bouclescence-photo-17','Halo Nocturne','Noir et ton doré','Anneau festonné','Un grand anneau noir festonné aux éclats dorés, en argile polymère avec des éléments en acier inoxydable. Une paire expressive qui encadre joliment le visage.','Son halo ouvert et ondulé offre une présence graphique tout en laissant passer la lumière, avec un noir profond ponctué de reflets dorés.'),
  ('bouclescence-photo-18','Flamme Corail','Corail orangé et ton doré','Fleur sculptée','Une fleur corail orangé aux accents dorés, façonnée en argile polymère et complétée d’éléments en acier inoxydable. Une paire chaleureuse et pleine d’élan.','Ses pétales sculptés s’ouvrent comme une flamme florale, dans un corail lumineux animé de petits détails à l’aspect doré.'),
  ('bouclescence-photo-19','Ronde Corail','Corail orangé et ton doré','Médaillon rond','Un médaillon corail orangé moucheté de doré, en argile polymère et acier inoxydable. Une forme ronde et lumineuse pour réveiller une tenue.','Son disque aux contours légèrement organiques affiche un corail franc, relevé de touches dorées et d’un élément supérieur rayonnant.'),
  ('bouclescence-photo-20','Éventail Fuchsia','Fuchsia et ton doré','Éventail','Un éventail fuchsia vibrant aux détails dorés, en argile polymère avec des éléments en acier inoxydable. Une paire joyeuse au graphisme affirmé.','Sa silhouette rayonnante, entre éventail et plumage stylisé, met à l’honneur un fuchsia intense ponctué de fins éclats dorés.'),
  ('bouclescence-photo-21','Lotus Fuchsia','Fuchsia et ton doré','Lotus','Un lotus fuchsia en relief suspendu à un feuillage doré, en argile polymère et acier inoxydable. Une création florale vive et féminine.','Trois grands pétales modelés composent une fleur fuchsia lumineuse, associée à un élément de feuillage fin à la finition dorée.'),
  ('bouclescence-photo-22','Pivoine Fuchsia','Fuchsia et ton doré','Fleur sculptée','Une pivoine fuchsia généreuse aux touches dorées, façonnée en argile polymère avec des éléments en acier inoxydable. Une paire florale pleine de tempérament.','Ses multiples pétales en relief donnent du volume à une fleur fuchsia éclatante, soulignée de détails dorés et d’un motif de feuillage.'),
  ('bouclescence-photo-23','Rosée','Rose poudré et ton doré','Fleur sculptée','Une fleur rose poudré délicatement ponctuée de doré, en argile polymère et acier inoxydable. Une paire tendre qui apporte une lumière douce au visage.','Sa floraison sculptée déploie de nombreux pétales rose pâle, avec de petites touches dorées et un élément supérieur en forme de feuillage.'),
  ('bouclescence-photo-24','Écarlate','Rouge écarlate et ton doré','Lotus','Un lotus rouge écarlate aux détails dorés, en argile polymère avec des éléments en acier inoxydable. Une paire lumineuse pour une allure assurée.','Ses pétales larges et dessinés en relief forment une fleur rouge intense, suspendue à un fin feuillage à la finition dorée.'),
  ('bouclescence-photo-25','Rubis Plissé','Rouge rubis et ton doré','Feuille striée','Une feuille rouge rubis finement striée et ponctuée de doré, façonnée en argile polymère et associée à l’acier inoxydable. Une ligne élancée et intense.','Sa forme pointue au relief plissé capte la lumière sur un rouge profond, tandis que quelques éclats dorés réchauffent l’ensemble.'),
  ('bouclescence-photo-26','Arc Émeraude','Vert émeraude et ton doré','Pétales et arcs','Des pétales vert émeraude associés à de fins arcs dorés, en argile polymère et acier inoxydable. Une composition graphique inspirée de l’Art déco.','Une petite fleur à trois pétales verts se superpose à un pendentif géométrique ajouré, rythmé par des arcs à la finition dorée.'),
  ('bouclescence-photo-27','Feuillage Émeraude','Vert émeraude et ton doré','Fleur sculptée','Une fleur vert émeraude aux contours dorés, façonnée en argile polymère avec des éléments en acier inoxydable. Une paire botanique profonde et élégante.','Ses nombreux pétales vert sombre dessinent une floraison généreuse, éclairée de liserés dorés et suspendue à un motif de feuillage.'),
  ('bouclescence-photo-28','Lotus Émeraude','Vert émeraude et ton doré','Lotus','Un lotus vert émeraude ponctué de doré, en argile polymère et acier inoxydable. Une paire végétale au relief délicat et à la couleur profonde.','Ses pétales superposés composent une fleur structurée en vert émeraude, reliée à un élément supérieur en forme de feuillage doré.'),
  ('bouclescence-photo-29','Amande Céladon','Céladon et ton doré','Lotus et arcs','Un lotus céladon associé à une grande composition d’arcs dorés, en argile polymère et acier inoxydable. Une paire aérienne au dessin géométrique.','La douceur du vert céladon contraste avec un large pendentif ajouré à la finition dorée, dont les arcs évoquent un éventail stylisé.'),
  ('bouclescence-photo-30','Feuille Olive','Vert olive et ton doré','Feuille striée','Une feuille vert olive au relief strié et aux éclats dorés, en argile polymère avec des éléments en acier inoxydable. Une paire naturelle et graphique.','Sa silhouette pointue, marquée de nervures régulières, met en valeur un vert olive frais ponctué de petites touches dorées.'),
  ('bouclescence-photo-31','Halo Olive','Vert olive et ton doré','Anneau festonné','Un grand halo vert olive aux contours festonnés et aux reflets dorés, façonné en argile polymère et associé à l’acier inoxydable. Une présence singulière.','Son anneau ouvert et ondulé dessine un cadre graphique autour du visage, dans un vert olive profond animé d’éclats dorés.'),
  ('bouclescence-photo-32','Amande Ivoire','Ivoire céladon et ton doré','Feuille striée','Une forme amande ivoire aux nuances céladon, finement striée et ponctuée de doré. L’argile polymère et l’acier inoxydable composent une paire douce.','Sa pièce élancée, entre amande et feuille, présente un relief nervuré et une teinte très pâle, éclairée par quelques accents dorés.'),
  ('bouclescence-photo-33','Dahlia Olive','Vert olive et ton doré','Fleur sculptée','Un dahlia vert olive aux détails dorés, en argile polymère avec des éléments en acier inoxydable. Une paire florale expressive aux nuances naturelles.','Ses pétales sculptés forment une fleur dense en vert olive, ponctuée de reflets dorés et suspendue à un délicat motif de feuillage.')
), updated as (
  update public.products p set
    short_description = c.short_description,
    description = c.visual_description || ' Façonnée en argile polymère et associée à des éléments en acier inoxydable, cette paire joue avec le relief et le mouvement sans surcharger la silhouette. Sa vue portée montre un tombé équilibré qui accompagne naturellement le visage. Elle complète aussi bien une tenue épurée, dont elle devient le point de couleur, qu’un ensemble plus habillé. Chaque détail visuel a été pensé pour conserver le caractère féminin, artisanal et chaleureux propre à l’univers Bouclescence.',
    main_material = 'Argile polymère',
    findings_material = 'Acier inoxydable',
    color = c.color,
    seo_title = c.model_name || ', boucles en argile polymère | Bouclescence',
    seo_description = 'Découvrez ' || c.model_name || ', des boucles d’oreilles en argile polymère ' || lower(c.color) || ' avec éléments en acier inoxydable, par Bouclescence.',
    updated_at = now()
  from content c where p.import_key = c.import_key
  returning p.id, p.import_key, c.model_name, c.color
)
update public.product_images i set
  alt_text = case when i.is_primary
    then 'Boucles d’oreilles ' || u.model_name || ' en argile polymère, ' || lower(u.color)
    else 'Boucles d’oreilles ' || u.model_name || ' portées'
  end
from updated u where i.product_id = u.id;

update public.collections set
  name = 'Boucles d’oreilles en argile polymère',
  description = 'Les créations Bouclescence en argile polymère, associées à des éléments en acier inoxydable.',
  introduction = 'Découvrez les boucles d’oreilles Bouclescence : des formes florales, graphiques et colorées en argile polymère, complétées par des éléments en acier inoxydable.',
  seo_content = 'Couleurs profondes, nuances douces, fleurs sculptées, feuilles striées et lignes géométriques composent cette collection. Chaque modèle possède sa propre silhouette et deux vues pour apprécier son dessin ainsi que son rendu porté.',
  seo_title = 'Boucles d’oreilles en argile polymère | Bouclescence',
  seo_description = 'Découvrez les boucles d’oreilles Bouclescence en argile polymère et acier inoxydable : des modèles floraux, graphiques et colorés à 15 €.',
  updated_at = now()
where slug = 'creations-bouclescence';

insert into public.collections (name,slug,description,introduction,seo_content,seo_title,seo_description,is_active,is_indexable,sort_order)
values
 ('Boucles colorées','boucles-colorees','Des boucles d’oreilles colorées pour illuminer chaque style.','Du bleu cobalt au fuchsia, du corail à l’émeraude, explorez les modèles Bouclescence où la couleur donne le ton.','Cette sélection réunit des créations en argile polymère aux nuances franches ou délicates, avec des éléments en acier inoxydable et des formes pensées pour mettre la couleur en mouvement.','Boucles d’oreilles colorées en argile polymère | Bouclescence','Explorez les boucles d’oreilles colorées Bouclescence en argile polymère : bleu, rose, corail, vert et autres nuances, avec acier inoxydable.',true,true,10),
 ('Boucles florales','boucles-florales','Des fleurs et pétales sculptés pour une allure délicate.','Lotus, dahlias, pivoines et pétales composent une sélection florale féminine et expressive.','Les reliefs de l’argile polymère permettent aux pétales et aux feuillages de prendre vie dans une palette douce ou intense. Chaque paire est complétée par des éléments en acier inoxydable.','Boucles d’oreilles florales en argile polymère | Bouclescence','Découvrez les boucles d’oreilles florales Bouclescence en argile polymère, inspirées des lotus, dahlias, pivoines et feuillages.',true,true,20)
on conflict (slug) do nothing;

insert into public.collection_products (collection_id,product_id,sort_order)
select c.id,p.id,substring(p.import_key from '[0-9]+$')::integer
from public.collections c cross join public.products p
where c.slug='boucles-colorees' and p.import_key ~ '^bouclescence-photo-([4-9]|1[0-4]|1[89]|2[0-9]|3[0-3])$'
on conflict (collection_id,product_id) do nothing;

insert into public.collection_products (collection_id,product_id,sort_order)
select c.id,p.id,substring(p.import_key from '[0-9]+$')::integer
from public.collections c cross join public.products p
where c.slug='boucles-florales' and p.import_key ~ '^bouclescence-photo-(1|6|7|8|10|11|12|15|18|21|22|23|24|27|28|29|33)$'
on conflict (collection_id,product_id) do nothing;
